### ISSUE TITLE
Support on UWP applications (xbox,pc,tablet,x86,x64,arm)?

### ISSUE THREAD

**Issue by TheCoder15** [M2Team/FFmpegUniversal#1]
Does this Support UWP applications (xbox,pc,tablet,x86,x64,arm)?
can i use it to merge downloaded Audio and video and output an MP4 file?

Thank you

**Comment by MouriNaruto** [comment]
Of course you can use it on an UWP app.
If you conform to the license.

**Comment by TheCoder15** [comment]
Thanks for your reply, sorry but what about my second question? if yes, any example?

**Comment by MouriNaruto** [comment]
Yes, but you should read the FFmpeg's documents first.
